# Generated by Django 6.1 on 2026-08-20 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='driving_category',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Light motorcycle'), ('A2', 'A2 - Motorcycle'), ('A3', 'A3 - Motorcycle (commercial)'), ('B1', 'B1 - Automatic car'), ('B2', 'B2 - Manual car'), ('B3', 'B3 - Professional light vehicle'), ('C1', 'C1 - Light truck'), ('C', 'C - Heavy truck'), ('CE', 'CE - Heavy truck + trailer'), ('D1', 'D1 - Small passenger vehicle'), ('D2', 'D2 - Medium passenger vehicle'), ('D', 'D - Large passenger vehicle'), ('E', 'E - Special/professional')], max_length=3),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('sign_in_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('status', models.CharField(choices=[('AWAITING', 'Awaiting Confirmation'), ('CONFIRMED', 'Confirmed Present')], default='AWAITING', max_length=10)),
                ('confirmation_time', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-sign_in_time'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
