# Generated by Django 6.1 on 2026-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_instructor_archived_at_instructor_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Awaiting Confirmation'), ('CONFIRMED', 'Confirmed Present'), ('DECLINED', 'Declined / Did Not Attend')], default='AWAITING', max_length=10),
        ),
    ]
